apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: get-ip-service
  namespace: ista
  labels:
    app: get-ip-service
spec:
  ingressClassName: nginx

  rules:
  # HTTP rule - replace example.com with your domain
  - host: kubernetes.istaacademy.com
    http:
      paths:
      - backend:
          service:
            name: get-ip-service
            port:
              number: 80
        path: /
        pathType: Prefix
